---
extends: default

ignore: |
  .travis.yml

rules:
  comments:
    min-spaces-from-content: 1
  document-start: disable
  line-length: disable
  truthy:
    allowed-values: ["true", "false", "on", "off"]
