---
name: "ZUnit (native)"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  zunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq zsh
          mkdir -p .bin
          curl -fsSL 'https://raw.githubusercontent.com/z-shell/revolver/master/revolver' > .bin/revolver
          curl -fsSL 'https://raw.githubusercontent.com/z-shell/color/master/color.zsh' > .bin/color
          chmod u+x .bin/{color,revolver}
      - name: Build
        run: ./build.zsh
      - name: Run test suite
        run: PATH="$PWD/.bin:$PATH" ./zunit --tap tests
